apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjp7ImF1dGgiOiJaRzl2WDNZeFh6UXpNalZoWldVellURTFPR1ptTW1Oa01EWTNZV0UzWmpOaFpHTXlOVFF4TWpOaU1qZ3pNak0wTmpNM1pUVmpPRFprTkRFek1EY3hZbU5pTnpZellqYzZaRzl2WDNZeFh6UXpNalZoWldVellURTFPR1ptTW1Oa01EWTNZV0UzWmpOaFpHTXlOVFF4TWpOaU1qZ3pNak0wTmpNM1pUVmpPRFprTkRFek1EY3hZbU5pTnpZellqYz0ifX19
kind: Secret
metadata:
  creationTimestamp: "2026-05-27T22:20:11Z"
  labels:
    digitalocean.com/copy-identifier: openzerg
  name: openzerg
  namespace: openzerg
  resourceVersion: "3337"
  uid: 1408e1af-0793-4117-8f3a-0e49d582ff3f
type: kubernetes.io/dockerconfigjson
